name: mixin_bot_sdk_dart
description: Mixin Messenger API for Dart/Flutter, build decentrialized applications on Mixin
version: 1.4.3
homepage: https://github.com/MixinNetwork/mixin_bot_sdk_dart

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  dart_jsonwebtoken: ">=2.12.2 <4.0.0"
  sprintf: ">=6.0.0 <8.0.0"
  uuid: ^4.4.2
  dio: ^5.9.1
  json_annotation: ^4.11.0
  crypto: ^3.0.7
  meta: ^1.4.0
  equatable: ^2.0.3
  enum_to_string: ^2.0.1
  recase: ^4.0.0
  ed25519_edwards: ^0.3.1
  collection: ^1.18.0
  x25519: ^0.1.1
  pointycastle: ">=3.7.4 <5.0.0"
  fixnum: ^1.0.1
  base_x: ^2.0.1
  decimal: ">=2.3.3 <4.0.0"
  thirds: ^0.2.0-alpha.1
  edwards25519: ^1.0.4

dev_dependencies:
  test: ^1.26.2
  very_good_analysis: ^10.2.0
  build_runner: ^2.11.1
  json_serializable: ^6.13.0
